### ISSUE TITLE
Support Heading?

### ISSUE THREAD

**Issue by afeezaziz** [WolfBearGames/Geolocation-GDScript-Wrapper#2]
Based on README, this wrapper does not support heading however,  based on example script:

`    geolocation_api.connect("heading_update", self, "_on_heading_update")`

there is a heading update. Please let us know on this matter.

**Comment by WolfBearGames** [comment]
heading should be supported (only on iOS!) but there is no convenient "heading_watcher" functionality.

**Comment by afeezaziz** [comment]
Thank you! Please do let me how can I contact you for bounty work.
